import type { NestedValueOf } from '@/utils/nested-value-of';

/**
 * This file is generated by packages/primitive/cli/generate-domain-codes.ts.
 * Do not edit this file manually.
 */
export const DomainComponentCode = {
  Account: {
    User: 'account:user',
    Auth: 'account:auth',
    UserNotification: 'account:user_notification',
  },
  Operation: {
    Config: 'operation:config',
    Notice: 'operation:notice',
    AuditLog: 'operation:audit_log',
    ShortLink: 'operation:short_link',
  },
  System: {
    Initialize: 'system:initialize',
    Shutdown: 'system:shutdown',
    Trigger: 'system:trigger',
    Exception: 'system:exception',
  },
  Persistence: {
    Database: 'persistence:database',
    Store: 'persistence:store',
    Cache: 'persistence:cache',
    Pubsub: 'persistence:pubsub',
    TaskQueue: 'persistence:task_queue',
  },
  Storage: {
    Storage: 'storage:storage',
    InternalStorage: 'storage:internal_storage',
    PrivateStorage: 'storage:private_storage',
    PublicStorage: 'storage:public_storage',
  },
  Notification: {
    Email: 'notification:email',
    Push: 'notification:push',
    DiscordWebhook: 'notification:discord_webhook',
    UserNotification: 'notification:user_notification',
    Sse: 'notification:sse',
  },
  Dev: {
    Devtools: 'dev:devtools',
    Test: 'dev:test',
  },
} as const;

export type DomainComponentCode = NestedValueOf<typeof DomainComponentCode>;
