/**
 * This file is generated by packages/primitive/cli/generate-domain-codes.ts.
 * Do not edit this file manually.
 */
export const DomainContextCode = {
  Account: 'account',
  Operation: 'operation',
  System: 'system',
  Persistence: 'persistence',
  Storage: 'storage',
  Notification: 'notification',
  Dev: 'dev',
} as const;
export type DomainContextCode = (typeof DomainContextCode)[keyof typeof DomainContextCode];
