import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DOMAIN_YAML_PATH = path.resolve(__dirname, '..', 'data', 'domain.yaml');
const DOMAIN_CONTEXT_CODE_PATH = path.resolve(
  __dirname,
  '..',
  'src',
  'codes',
  'domain-context',
  'domain-context-codes.ts',
);
const DOMAIN_COMPONENT_CODE_PATH = path.resolve(
  __dirname,
  '..',
  'src',
  'codes',
  'domain-component',
  'domain-component-codes.ts',
);

const DOMAIN_COMPONENT_CODE_HEADER = `import type { NestedValueOf } from '@/utils/nested-value-of';`;

const WARNING_HEADER = `/**
 * This file is generated by packages/primitive/cli/generate-domain-codes.ts.
 * Do not edit this file manually.
 */
`;

interface Domain {
  [key: string]: {
    components?: {
      [key: string]: unknown;
    };
  };
}

interface DomainYaml {
  business: Domain;
  platform: Domain;
}

function toPascalCase(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function generateDomainContextCode(domainYaml: DomainYaml): string {
  const contexts = [...Object.keys(domainYaml.business), ...Object.keys(domainYaml.platform)];
  let content = WARNING_HEADER;
  content += 'export const DomainContextCode = {\n';
  for (const context of contexts) {
    content += `  ${toPascalCase(context)}: '${context}',\n`;
  }
  content += '} as const;\n';
  content +=
    'export type DomainContextCode = (typeof DomainContextCode)[keyof typeof DomainContextCode];\n';
  return content;
}

function generateDomainComponentCode(domainYaml: DomainYaml): string {
  let content = DOMAIN_COMPONENT_CODE_HEADER + '\n\n';
  content += WARNING_HEADER;
  content += 'export const DomainComponentCode = {\n';

  for (const context of Object.keys(domainYaml.business)) {
    content += `  ${toPascalCase(context)}: {\n`;
    if (domainYaml.business[context]!.components) {
      for (const component of Object.keys(domainYaml.business[context]!.components)) {
        content += `    ${toPascalCase(component)}: '${context}:${component}',\n`;
      }
    }
    content += '  },\n';
  }

  for (const context of Object.keys(domainYaml.platform)) {
    content += `  ${toPascalCase(context)}: {\n`;
    if (domainYaml.platform[context]!.components) {
      for (const component of Object.keys(domainYaml.platform[context]!.components)) {
        content += `    ${toPascalCase(component)}: '${context}:${component}',\n`;
      }
    }
    content += '  },\n';
  }
  content += '} as const;\n\n';
  content += `export type DomainComponentCode = NestedValueOf<typeof DomainComponentCode>;
`;
  return content;
}

async function main() {
  try {
    const fileContents = await fs.readFile(DOMAIN_YAML_PATH, 'utf8');
    const domainYaml = yaml.load(fileContents) as DomainYaml;

    const domainContextCode = generateDomainContextCode(domainYaml);
    await fs.writeFile(DOMAIN_CONTEXT_CODE_PATH, domainContextCode);
    console.log(`Generated ${DOMAIN_CONTEXT_CODE_PATH}`);

    const domainComponentCode = generateDomainComponentCode(domainYaml);
    await fs.writeFile(DOMAIN_COMPONENT_CODE_PATH, domainComponentCode);
    console.log(`Generated ${DOMAIN_COMPONENT_CODE_PATH}`);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
}

main();
